language: node_js
node_js:
  - "7"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project 1//0fQocRlPTBoyvCgYIARAAGA8SNwF-L9IrvBD_DNcyN9pDsLg8uTRzcHoLkg7ApQaDIA7v-Bz3RMHQZHu2XG04VRE6q8esfUjYiG0 --token $FIREBASE_TOKEN
